esphome:
  name: esp-alarmlicht
 
http_request:
  useragent: esphome/esp-alarmlicht

esp32:
  board: esp32-evb
  framework:
    type: arduino

globals:
  - id: global_send_divera_testalarm
    type: bool
    initial_value: 'false'
  - id: global_send_ntfy_testalarm
    type: bool
    initial_value: 'false'
  - id: global_send_divera_alarm
    type: bool
    initial_value: 'false'
  - id: global_send_ntfy_alarm
    type: bool
    initial_value: 'false'

# Enable logging
logger:

wifi:
  networks:
    - ssid: !secret first_wifi_ssid
      password: !secret first_wifi_password
    - ssid: !secret second_wifi_ssid
      password: !secret second_wifi_password


output:
  - platform: gpio
    id: output_gpio23
    pin: GPIO23
    inverted: True
  - platform: gpio
    id: alarm_led
    pin: GPIO21
    inverted: True
  - platform: gpio
    id: wifi_connected_led
    pin: GPIO26
    inverted: True

light:
  - platform: binary
    output: output_gpio23
    id: testbutton_led
    restore_mode: ALWAYS_ON

# When the  BUT1 is pressed, trigger two alarms
binary_sensor:
  - platform: gpio
    pin: GPIO34
    name: "Testalarm"
    on_press: 
        !include 
          file: on-but1-press.yaml
          vars:  
            divera_type: "🤷Testalarm (🔘 am Alarmlicht)🤷"
            ntfy_title: "🤷Testalarm (🔘 am Alarmlicht 2.0)🤷"
            ntfy_priority: "default"
            ntfy_tags: "loudspeaker, construction"
            ntfy_body: "Es drückte jemand den Testbutton am ESP-Alarmlicht."
    on_release: 
      then:
        - light.turn_off: testbutton_led
          
        

