esphome:
  name: alarmlicht

http_request:
  useragent: esphome/alarmlicht
  

esp32:
  board: esp32-evb
  framework:
    type: arduino

# Enable logging
logger:


wifi:
  networks:
  - ssid: !secret first_wifi_ssid
    password: !secret first_wifi_password
  - ssid: !secret second_wifi_ssid
    password: !secret second_wifi_password
  
# When the  BUT1 is pressed, trigger two alarms
binary_sensor:
  - platform: gpio
    pin: GPIO34
    name: "Testalarm"
    on_press:
      - logger.log: "Testalarm button pressed"
      - http_request.post:
          url: !secret divera_alarm_api_url
          verify_ssl: false
          headers:
            Content-Type: application/json
          json:
            type: "🤷Testalarm (🔘 am Alarmlicht)🤷"
          on_response:
            then:
              - logger.log:
                  format: 'Response status: %d, Duration: %u ms'
                  args:
                    - status_code
                    - duration_ms
      - http_request.send:
          method: PUT
          url: !secret ntfy_url
          verify_ssl: false
          headers: 
            Title: "🤷Testalarm (🔘 am Alarmlicht 2.0)🤷"
            Priority: "default"
            Tags: "loudspeaker, construction"
          body: "Es drückte jemand den Testbutton am Alarmlicht 2.0"
          on_response:
            then:
              - logger.log:
                  format: 'Response status: %d, Duration: %u ms'
                  args:
                    - status_code
                    - duration_ms
    

    