esphome:
  name: esp-alarmlicht
  on_boot: 
    then:
      # disable all LEDs on boot
      - output.turn_off: testbutton_led
      - output.turn_off: alarm_led
      - output.turn_off: wifi_connected_led
      - output.turn_off: relay_1 
 
http_request:
  useragent: esphome/esp-alarmlicht

esp32:
  board: esp32-evb
  framework:
    type: arduino

globals:
  - id: global_send_divera_testalarm
    type: bool
    initial_value: 'false'
  - id: global_send_ntfy_testalarm
    type: bool
    initial_value: 'false'
  - id: global_send_divera_alarm
    type: bool
    initial_value: 'false'
  - id: global_send_ntfy_alarm
    type: bool
    initial_value: 'false'

# Enable logging
logger:

wifi:
  networks:
    - ssid: !secret first_wifi_ssid
      password: !secret first_wifi_password
    - ssid: !secret second_wifi_ssid
      password: !secret second_wifi_password


output:
  - platform: gpio
    id: testbutton_led
    pin: GPIO23
  - platform: gpio
    id: alarm_led
    pin: GPIO21
  - platform: gpio
    id: wifi_connected_led
    pin: GPIO14
  - platform: gpio
    id: relay_1
    pin: GPIO32

# light:
#   - platform: binary
#     output: output_gpio23
#     id: testbutton_led
#     restore_mode: ALWAYS_ON

interval:
  - interval: 3s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - output.turn_on: wifi_connected_led
          - delay: 0.05s
          - output.turn_off: wifi_connected_led
        else:
          - output.turn_off: wifi_connected_led

# When the  BUT1 is pressed, trigger two alarms
binary_sensor:
  - platform: gpio
    pin: GPIO34
    name: "Button 1"
    filters:
      - invert:
    on_press: 
        !include 
          file: on-but1-press.yaml
          vars:  
            divera_type: "🤷Testalarm (🔘 am Alarmlicht)🤷"
            ntfy_title: "🤷Testalarm (🔘 am Alarmlicht 2.0)🤷"
            ntfy_priority: "default"
            ntfy_tags: "loudspeaker, construction"
            ntfy_body: "Es drückte jemand den Testbutton am ESP-Alarmlicht."
    on_release: 
      then:
        - output.turn_off: testbutton_led
        - output.turn_off: wifi_connected_led
        - output.turn_off: alarm_led
  - platform: gpio
    pin: GPIO16
    name: "Funklicht"
    filters:
      - invert:
    on_press:
    # todo: nur das relais schalten (alarmlicht muss an gehen)
      - output.turn_on: testbutton_led
    on_release: 
      then:
        - output.turn_off: testbutton_led
  - platform: gpio
    pin: GPIO18
    name: "DME Relais"
    filters:
      - invert:
    on_press: 
    # todo: http requests auslösen relais schalten (alarmlicht muss an gehen)
      - output.turn_on: alarm_led
    on_release: 
      then:
        - output.turn_off: alarm_led

