esphome:
  name: esp-alarmlicht

http_request:
  useragent: esphome/esp-alarmlicht

esp32:
  board: esp32-evb
  framework:
    type: arduino

globals:
  - id: global_send_divera_testalarm
    type: bool
    initial_value: 'false'
  - id: global_send_ntfy_testalarm
    type: bool
    initial_value: 'true'
  - id: global_send_divera_alarm
    type: bool
    initial_value: 'true'
  - id: global_send_ntfy_alarm
    type: bool
    initial_value: 'true'

# Enable logging
logger:

wifi:
  networks:
    - ssid: !secret first_wifi_ssid
      password: !secret first_wifi_password
    - ssid: !secret second_wifi_ssid
      password: !secret second_wifi_password

# When the  BUT1 is pressed, trigger two alarms
binary_sensor:
  - platform: gpio
    pin: GPIO34
    name: "Testalarm"
    on_press: 
        !include 
          file: on-but1-press.yaml
          vars:  
            divera_type: "🤷Testalarm (🔘 am Alarmlicht)🤷"
            ntfy_title: "🤷Testalarm (🔘 am Alarmlicht 2.0)🤷"
            ntfy_priority: "default"
            ntfy_tags: "loudspeaker, construction"
            ntfy_body: "Es drückte jemand den Testbutton am ESP-Alarmlicht."
          
        

